---
title: "get_data"
author: "Xiaohao Yang"
vignette: >
  %\VignetteIndexEntry{greenSD}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

# Donwload multi-band data from Greenspace Seasonality Data Cube with specified area/point of inerest
This may take more than 5 minutes.

```{r eval=FALSE}
gs <- greenSD::get_gsds_data(bbox = c(-83.272828,42.343950,-83.218926,42.379719), year = 2022, mask = TRUE)
```

```{r eval=FALSE}
gs <- greenSD::get_gsds_data(place = 'Detroit', year = 2022)
```

```{r eval=FALSE}
gs <- greenSD::get_gsds_data(location = c(-83.10215 42.38342), year = 2022)
```

```{r eval=FALSE}
# greenSD::check_available_cities()
gs <- greenSD::get_gsds_data(UID = 1825, year = 2022, time = c("03-01", "09-01"))
```

# Extract values from Greenspace Seasonality Data Cube with samples
```{r eval=FALSE}
boundary <- greenSD::check_urban_boundary(uid = 1825, plot = FALSE)
samples <- sf::st_sample(boundary, size = 50)
gs_samples <- greenSD::sample_values(samples, year = 2022)
```
