testthat::test_that("runs correctly", {
  city <- greenSD::get_gsdc()
  esa <- greenSD::get_esa_wc()
  s2a <- greenSD::get_s2a_ndvi()
  sample <- greenSD::sample_values()
  sem <- greenSD::lc_sem_seg()
  pwgf <- greenSD::exposure()
  testthat::expect_type(city, "NULL")
  testthat::expect_type(esa, "NULL")
  testthat::expect_type(s2a, "NULL")
  testthat::expect_type(sem, "NULL")
  testthat::expect_type(sample, "NULL")
  testthat::expect_type(pwgf, "NULL")
})
